//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FleetManager.ExternalServices.GroupwareMailService
{

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionInfo", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class ConnectionInfo : object
    {
        
        private GroupwareMailService.Credentials CredentialsField;
        
        private string TargetMailboxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Credentials Credentials
        {
            get
            {
                return this.CredentialsField;
            }
            set
            {
                this.CredentialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetMailbox
        {
            get
            {
                return this.TargetMailboxField;
            }
            set
            {
                this.TargetMailboxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class Credentials : object
    {
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class TargetMailboxNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParentFolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class ParentFolderNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class AccessDenied : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolderAlreadyExists", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class FolderAlreadyExists : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class InvalidCredentials : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class InvalidInput : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class FolderNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationNotAllowed", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class OperationNotAllowed : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DestinationFolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class DestinationFolderNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidOperation", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class InvalidOperation : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistinguishedFolderName", Namespace="http://www.b-holding.be/A882/Mail")]
    public enum DistinguishedFolderName : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeletedItems = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Drafts = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inbox = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JunkEmail = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbox = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentItems = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatFolder", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class FlatFolder : object
    {
        
        private string FolderIdField;
        
        private string FolderNameField;
        
        private string ParentFolderIdField;
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderId
        {
            get
            {
                return this.FolderIdField;
            }
            set
            {
                this.FolderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName
        {
            get
            {
                return this.FolderNameField;
            }
            set
            {
                this.FolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentFolderId
        {
            get
            {
                return this.ParentFolderIdField;
            }
            set
            {
                this.ParentFolderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HierarchicalFolder", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class HierarchicalFolder : object
    {
        
        private string FolderIdField;
        
        private string FolderNameField;
        
        private GroupwareMailService.HierarchicalFolder[] SubfoldersField;
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderId
        {
            get
            {
                return this.FolderIdField;
            }
            set
            {
                this.FolderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName
        {
            get
            {
                return this.FolderNameField;
            }
            set
            {
                this.FolderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.HierarchicalFolder[] Subfolders
        {
            get
            {
                return this.SubfoldersField;
            }
            set
            {
                this.SubfoldersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class OperationResult : object
    {
        
        private string ItemIdField;
        
        private string MessageField;
        
        private string NewItemIdField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewItemId
        {
            get
            {
                return this.NewItemIdField;
            }
            set
            {
                this.NewItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForwardMailInfo", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class ForwardMailInfo : object
    {
        
        private string BodyPrefixField;
        
        private string EmailIdField;
        
        private string[] ToRecipientsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyPrefix
        {
            get
            {
                return this.BodyPrefixField;
            }
            set
            {
                this.BodyPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId
        {
            get
            {
                return this.EmailIdField;
            }
            set
            {
                this.EmailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ToRecipients
        {
            get
            {
                return this.ToRecipientsField;
            }
            set
            {
                this.ToRecipientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailNotFound", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class EmailNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReplyMailInfo", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class ReplyMailInfo : object
    {
        
        private string BodyPrefixField;
        
        private string EmailIdField;
        
        private bool ReplyToAllField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyPrefix
        {
            get
            {
                return this.BodyPrefixField;
            }
            set
            {
                this.BodyPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId
        {
            get
            {
                return this.EmailIdField;
            }
            set
            {
                this.EmailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReplyToAll
        {
            get
            {
                return this.ReplyToAllField;
            }
            set
            {
                this.ReplyToAllField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentDetails", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class AttachmentDetails : object
    {
        
        private string AttachmentIdField;
        
        private byte[] BytesField;
        
        private string MimeTypeField;
        
        private string NameField;
        
        private string OwnerIdField;
        
        private int SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentId
        {
            get
            {
                return this.AttachmentIdField;
            }
            set
            {
                this.AttachmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentNotFound", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class AttachmentNotFound : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class Email : object
    {
        
        private string EmailIdField;
        
        private bool HasAttachmentsField;
        
        private GroupwareMailService.Importance ImportanceField;
        
        private System.DateTime ReceivedDateField;
        
        private string SenderNameField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId
        {
            get
            {
                return this.EmailIdField;
            }
            set
            {
                this.EmailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAttachments
        {
            get
            {
                return this.HasAttachmentsField;
            }
            set
            {
                this.HasAttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Importance Importance
        {
            get
            {
                return this.ImportanceField;
            }
            set
            {
                this.ImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceivedDate
        {
            get
            {
                return this.ReceivedDateField;
            }
            set
            {
                this.ReceivedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Importance", Namespace="http://www.b-holding.be/A882/Mail")]
    public enum Importance : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDetails", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class EmailDetails : object
    {
        
        private GroupwareMailService.Attachment[] AttachmentsField;
        
        private string BodyField;
        
        private GroupwareMailService.Recipient[] CCRecipientsField;
        
        private System.DateTime CreatedDateField;
        
        private string EmailIdField;
        
        private GroupwareMailService.Importance ImportanceField;
        
        private System.DateTime ReceivedDateField;
        
        private string SenderEmailAddressField;
        
        private string SenderNameField;
        
        private System.DateTime SentDateField;
        
        private string SubjectField;
        
        private GroupwareMailService.Recipient[] ToRecipientsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Attachment[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Recipient[] CCRecipients
        {
            get
            {
                return this.CCRecipientsField;
            }
            set
            {
                this.CCRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId
        {
            get
            {
                return this.EmailIdField;
            }
            set
            {
                this.EmailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Importance Importance
        {
            get
            {
                return this.ImportanceField;
            }
            set
            {
                this.ImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReceivedDate
        {
            get
            {
                return this.ReceivedDateField;
            }
            set
            {
                this.ReceivedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmailAddress
        {
            get
            {
                return this.SenderEmailAddressField;
            }
            set
            {
                this.SenderEmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentDate
        {
            get
            {
                return this.SentDateField;
            }
            set
            {
                this.SentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Recipient[] ToRecipients
        {
            get
            {
                return this.ToRecipientsField;
            }
            set
            {
                this.ToRecipientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachment", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class Attachment : object
    {
        
        private string AttachmentIdField;
        
        private string NameField;
        
        private string OwnerIdField;
        
        private int SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentId
        {
            get
            {
                return this.AttachmentIdField;
            }
            set
            {
                this.AttachmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipient", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class Recipient : object
    {
        
        private string EmailAddressField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMailInfo", Namespace="http://www.b-holding.be/A882/Mail")]
    public partial class SendMailInfo : object
    {
        
        private GroupwareMailService.AttachmentInfo[] AttachmentsField;
        
        private string[] BccRecipientsField;
        
        private string BodyField;
        
        private string[] CCRecipientsField;
        
        private GroupwareMailService.Importance ImportanceField;
        
        private string SubjectField;
        
        private string[] ToRecipientsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.AttachmentInfo[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BccRecipients
        {
            get
            {
                return this.BccRecipientsField;
            }
            set
            {
                this.BccRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CCRecipients
        {
            get
            {
                return this.CCRecipientsField;
            }
            set
            {
                this.CCRecipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GroupwareMailService.Importance Importance
        {
            get
            {
                return this.ImportanceField;
            }
            set
            {
                this.ImportanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ToRecipients
        {
            get
            {
                return this.ToRecipientsField;
            }
            set
            {
                this.ToRecipientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentInfo", Namespace="http://www.b-holding.be/A882/Core")]
    public partial class AttachmentInfo : object
    {
        
        private byte[] BytesField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.b-holding.be/A882/Mail", ConfigurationName="GroupwareMailService.IMailService")]
    public interface IMailService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolder", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderTargetMailboxNotFoundF" +
            "ault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.ParentFolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderParentFolderNotFoundFa" +
            "ult", Name="ParentFolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderAccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderAlreadyExists), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderFolderAlreadyExistsFau" +
            "lt", Name="FolderAlreadyExists", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderInvalidCredentialsFaul" +
            "t", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/CreateFolderInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<string> CreateFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderName, string parentFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolder", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderFolderNotFoundFault", Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderAccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderInvalidCredentialsFaul" +
            "t", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.OperationNotAllowed), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteFolderOperationNotAllowedFau" +
            "lt", Name="OperationNotAllowed", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task DeleteFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolder", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.OperationNotAllowed), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderOperationNotAllowedFault" +
            "", Name="OperationNotAllowed", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.DestinationFolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderDestinationFolderNotFoun" +
            "dFault", Name="DestinationFolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderAlreadyExists), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderFolderAlreadyExistsFault" +
            "", Name="FolderAlreadyExists", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderFolderNotFoundFault", Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderInvalidCredentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidOperation), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveFolderInvalidOperationFault", Name="InvalidOperation", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task MoveFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId, string destinationFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolder", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderFolderNotFoundFault", Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.OperationNotAllowed), Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderOperationNotAllowedFau" +
            "lt", Name="OperationNotAllowed", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderAlreadyExists), Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderFolderAlreadyExistsFau" +
            "lt", Name="FolderAlreadyExists", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderInvalidCredentialsFaul" +
            "t", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RenameFolderInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task RenameFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId, string newFolderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedName", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedNameR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedNameI" +
            "nvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedNameA" +
            "ccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedNameI" +
            "nvalidCredentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByDistinguishedNameT" +
            "argetMailboxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.FlatFolder> RetrieveFolderByDistinguishedNameAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.DistinguishedFolderName distinguishedName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderById", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByIdFolderNotFoundFa" +
            "ult", Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByIdInvalidInputFaul" +
            "t", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderByIdInvalidCredentia" +
            "lsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.FlatFolder> RetrieveFolderByIdAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchy", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchyTargetMailb" +
            "oxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchyAccessDenie" +
            "dFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchyInvalidCred" +
            "entialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFolderHierarchyInvalidInpu" +
            "tFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.HierarchicalFolder[]> RetrieveFolderHierarchyAsync(GroupwareMailService.ConnectionInfo connectionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByName", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByNameInvalidInputF" +
            "ault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByNameAccessDeniedF" +
            "ault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByNameTargetMailbox" +
            "NotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByNameInvalidCreden" +
            "tialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.FlatFolder[]> RetrieveFoldersByNameAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByParent", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByParentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.ParentFolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByParentParentFolde" +
            "rNotFoundFault", Name="ParentFolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByParentInvalidInpu" +
            "tFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveFoldersByParentInvalidCred" +
            "entialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.FlatFolder[]> RetrieveFoldersByParentAsync(GroupwareMailService.ConnectionInfo connectionInfo, string parentFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteMails", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/DeleteMailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteMailsInvalidCredentialsFault" +
            "", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/DeleteMailsInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.OperationResult[]> DeleteMailsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/ForwardMail", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/ForwardMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.EmailNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/ForwardMailEmailNotFoundFault", Name="EmailNotFound")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/ForwardMailAccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/ForwardMailInvalidCredentialsFault" +
            "", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/ForwardMailInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task ForwardMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.ForwardMailInfo forwardMailInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/MoveMails", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/MoveMailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveMailsInvalidCredentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/MoveMailsInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.OperationResult[]> MoveMailsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds, string destinationFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/ReplyMail", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/ReplyMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/ReplyMailInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/ReplyMailAccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.EmailNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/ReplyMailEmailNotFoundFault", Name="EmailNotFound")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/ReplyMailInvalidCredentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task ReplyMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.ReplyMailInfo replyMailInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentById", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AttachmentNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdAttachmentNo" +
            "tFoundFault", Name="AttachmentNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdAccessDenied" +
            "Fault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdInvalidInput" +
            "Fault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.EmailNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdEmailNotFoun" +
            "dFault", Name="EmailNotFound")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveAttachmentByIdInvalidCrede" +
            "ntialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.AttachmentDetails> RetrieveAttachmentByIdAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailId, string attachmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMail", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailInvalidC" +
            "redentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.EmailNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailEmailNot" +
            "FoundFault", Name="EmailNotFound")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailInvalidI" +
            "nputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailTargetMa" +
            "ilboxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveConversationByMailAccessDe" +
            "niedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveConversationByMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolder", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.FolderNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolderFolderNotFoun" +
            "dFault", Name="FolderNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolderInvalidInputF" +
            "ault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolderInvalidCreden" +
            "tialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByFolderAccessDeniedF" +
            "ault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByIds", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByIdsAccessDeniedFaul" +
            "t", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByIdsInvalidInputFaul" +
            "t", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByIdsInvalidCredentia" +
            "lsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.EmailDetails[]> RetrieveMailsByIdsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywords", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywordsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywordsTargetMailb" +
            "oxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywordsAccessDenie" +
            "dFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywordsInvalidCred" +
            "entialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByKeywordsInvalidInpu" +
            "tFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByKeywordsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipient", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipientInvalidInp" +
            "utFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipientTargetMail" +
            "boxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipientAccessDeni" +
            "edFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByRecipientInvalidCre" +
            "dentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByRecipientAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubject", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubjectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubjectInvalidInput" +
            "Fault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubjectTargetMailbo" +
            "xNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubjectAccessDenied" +
            "Fault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsBySubjectInvalidCrede" +
            "ntialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsBySubjectAsync(GroupwareMailService.ConnectionInfo connectionInfo, string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindow", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindowInvalidCr" +
            "edentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.TargetMailboxNotFound), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindowTargetMai" +
            "lboxNotFoundFault", Name="TargetMailboxNotFound", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindowAccessDen" +
            "iedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/RetrieveMailsByTimeWindowInvalidIn" +
            "putFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByTimeWindowAsync(GroupwareMailService.ConnectionInfo connectionInfo, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.b-holding.be/A882/Mail/IMailService/SendMail", ReplyAction="http://www.b-holding.be/A882/Mail/IMailService/SendMailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidInput), Action="http://www.b-holding.be/A882/Mail/IMailService/SendMailInvalidInputFault", Name="InvalidInput", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.AccessDenied), Action="http://www.b-holding.be/A882/Mail/IMailService/SendMailAccessDeniedFault", Name="AccessDenied", Namespace="http://www.b-holding.be/A882/Core")]
        [System.ServiceModel.FaultContractAttribute(typeof(GroupwareMailService.InvalidCredentials), Action="http://www.b-holding.be/A882/Mail/IMailService/SendMailInvalidCredentialsFault", Name="InvalidCredentials", Namespace="http://www.b-holding.be/A882/Core")]
        System.Threading.Tasks.Task SendMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.SendMailInfo sendMailInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IMailServiceChannel : GroupwareMailService.IMailService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<GroupwareMailService.IMailService>, GroupwareMailService.IMailService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailServiceClient() : 
                base(MailServiceClient.GetDefaultBinding(), MailServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_IMailService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MailServiceClient.GetBindingForEndpoint(endpointConfiguration), MailServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> CreateFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderName, string parentFolderId)
        {
            return base.Channel.CreateFolderAsync(connectionInfo, folderName, parentFolderId);
        }
        
        public System.Threading.Tasks.Task DeleteFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId)
        {
            return base.Channel.DeleteFolderAsync(connectionInfo, folderId);
        }
        
        public System.Threading.Tasks.Task MoveFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId, string destinationFolderId)
        {
            return base.Channel.MoveFolderAsync(connectionInfo, folderId, destinationFolderId);
        }
        
        public System.Threading.Tasks.Task RenameFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId, string newFolderName)
        {
            return base.Channel.RenameFolderAsync(connectionInfo, folderId, newFolderName);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.FlatFolder> RetrieveFolderByDistinguishedNameAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.DistinguishedFolderName distinguishedName)
        {
            return base.Channel.RetrieveFolderByDistinguishedNameAsync(connectionInfo, distinguishedName);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.FlatFolder> RetrieveFolderByIdAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId)
        {
            return base.Channel.RetrieveFolderByIdAsync(connectionInfo, folderId);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.HierarchicalFolder[]> RetrieveFolderHierarchyAsync(GroupwareMailService.ConnectionInfo connectionInfo)
        {
            return base.Channel.RetrieveFolderHierarchyAsync(connectionInfo);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.FlatFolder[]> RetrieveFoldersByNameAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderName)
        {
            return base.Channel.RetrieveFoldersByNameAsync(connectionInfo, folderName);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.FlatFolder[]> RetrieveFoldersByParentAsync(GroupwareMailService.ConnectionInfo connectionInfo, string parentFolderId)
        {
            return base.Channel.RetrieveFoldersByParentAsync(connectionInfo, parentFolderId);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.OperationResult[]> DeleteMailsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds)
        {
            return base.Channel.DeleteMailsAsync(connectionInfo, emailIds);
        }
        
        public System.Threading.Tasks.Task ForwardMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.ForwardMailInfo forwardMailInfo)
        {
            return base.Channel.ForwardMailAsync(connectionInfo, forwardMailInfo);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.OperationResult[]> MoveMailsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds, string destinationFolderId)
        {
            return base.Channel.MoveMailsAsync(connectionInfo, emailIds, destinationFolderId);
        }
        
        public System.Threading.Tasks.Task ReplyMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.ReplyMailInfo replyMailInfo)
        {
            return base.Channel.ReplyMailAsync(connectionInfo, replyMailInfo);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.AttachmentDetails> RetrieveAttachmentByIdAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailId, string attachmentId)
        {
            return base.Channel.RetrieveAttachmentByIdAsync(connectionInfo, emailId, attachmentId);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveConversationByMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailId)
        {
            return base.Channel.RetrieveConversationByMailAsync(connectionInfo, emailId);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByFolderAsync(GroupwareMailService.ConnectionInfo connectionInfo, string folderId)
        {
            return base.Channel.RetrieveMailsByFolderAsync(connectionInfo, folderId);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.EmailDetails[]> RetrieveMailsByIdsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] emailIds)
        {
            return base.Channel.RetrieveMailsByIdsAsync(connectionInfo, emailIds);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByKeywordsAsync(GroupwareMailService.ConnectionInfo connectionInfo, string[] keywords)
        {
            return base.Channel.RetrieveMailsByKeywordsAsync(connectionInfo, keywords);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByRecipientAsync(GroupwareMailService.ConnectionInfo connectionInfo, string emailAddress)
        {
            return base.Channel.RetrieveMailsByRecipientAsync(connectionInfo, emailAddress);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsBySubjectAsync(GroupwareMailService.ConnectionInfo connectionInfo, string subject)
        {
            return base.Channel.RetrieveMailsBySubjectAsync(connectionInfo, subject);
        }
        
        public System.Threading.Tasks.Task<GroupwareMailService.Email[]> RetrieveMailsByTimeWindowAsync(GroupwareMailService.ConnectionInfo connectionInfo, System.DateTime startTime, System.DateTime endTime)
        {
            return base.Channel.RetrieveMailsByTimeWindowAsync(connectionInfo, startTime, endTime);
        }
        
        public System.Threading.Tasks.Task SendMailAsync(GroupwareMailService.ConnectionInfo connectionInfo, GroupwareMailService.SendMailInfo sendMailInfo)
        {
            return base.Channel.SendMailAsync(connectionInfo, sendMailInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IMailService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap11, System.ServiceModel.Channels.AddressingVersion.WSAddressing10);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IMailService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("urn:www.infrabel.be:A882:Mail"), new System.ServiceModel.DnsEndpointIdentity("SYS_A882-BCAExchange"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MailServiceClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_IMailService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MailServiceClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_IMailService);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_IMailService,
        }
    }
}
